RAGbasedResumeEditor/resumeEditorBackend

backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeEditController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/Resume.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeBoard.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeEdit.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeBoardDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeEditDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeBoardRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeEditRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeServiceImpl.java

resume add

---

backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/JWTFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/main/java/com/team2/resumeeditorproject/user/dto/CustomUserDetails.java
backend/src/main/java/com/team2/resumeeditorproject/user/dto/UserDTO.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/CustomUserDetailsService.java

jwt토큰 생명주기 수정, response body 추가

login update

---

backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/ReissueController.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java

jwt update

---

backend/build.gradle
backend/src/main/java/com/team2/resumeeditorproject/gpt/controller/ChatController.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/controller/ChatGPTController.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/dto/ChatRequestMsgDto.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/AdvancedRagService.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/BasicRagService.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/ChatConstants.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/ChatGPTService.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/ChatService.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/DataIngestionService.java
backend/src/main/java/com/team2/resumeeditorproject/gpt/service/RagService.java

userController push

---

backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/MailController.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/MailServiceImpl.java

"https://resume-editor-frontend-indol.vercel.app" => / 제거
"/signup" 추가

deploy test

---

backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeEditController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/Rating.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/RatingId.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/Resume.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeBoard.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/RatingDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeBoardDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/RatingRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeBoardRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/RatingService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/RatingServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardServiceImpl.java

Resume board2

---

backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeEditRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserReposotory.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/resources/application.yml

admin repository updates

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/ResumeManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java

Admin resume list

---

backend/src/main/java/com/team2/resumeeditorproject/comment/controller/CommentController.java
backend/src/main/java/com/team2/resumeeditorproject/comment/repository/CommentRepository.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/UserServiceImpl.java

resume-board 4

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/ResumeManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/ResponseHandler.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/MailController.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java

controllers updates

---

backend/build.gradle
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/UserService.java
backend/src/main/resources/application.yml

admin statistic updates

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/ResumeManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/ResumeManagementServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java

admin controllers updates

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeEditRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/main/java/com/team2/resumeeditorproject/user/domain/User.java
backend/src/main/java/com/team2/resumeeditorproject/user/dto/CustomUserDetails.java

refresh 이슈 수정, 탈퇴회원 로그인 실패 수정
관리자 페이지 - 회원목록 수정, 첨삭횟수 통계 추가

refresh update and admin history update

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeEditRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/JWTUtil.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/ReissueController.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/RefreshRepository.java

토큰에 mode 추가, 회원탈퇴 수정, 회원목록 페이징,정렬 수정, 자소서첨삭 통계 추가

refresh, admin history update

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/comment/controller/CommentController.java
backend/src/main/java/com/team2/resumeeditorproject/comment/repository/CommentRepository.java
backend/src/main/java/com/team2/resumeeditorproject/comment/service/CommentService.java
backend/src/main/java/com/team2/resumeeditorproject/comment/service/CommentServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeEditController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeBoardRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/domain/User.java

resume ranking, resume comment update

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementServiceImpl.java

관리자페이지에서 회원 탈퇴시 role변경(role_blacklist), 회원목록 수정, 첨삭횟수/비율 response 수정

user role update, resume edit count/ratio update

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/UserManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/Error/UserBlacklistedException.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/CustomAuthenticationFailureHandler.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/CustomAuthenticationProvider.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/dto/CustomUserDetails.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/UserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/CustomUserDetailsService.java

role_blacklist 처리 수정, 로그인 시 예외처리 수정, 자소서첨삭 통계 수정

role_blacklist update, admin history update

---

backend/src/main/java/com/team2/resumeeditorproject/exception/ControllerExceptionAdvice.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/main/java/com/team2/resumeeditorproject/user/domain/User.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/UserServiceImpl.java

mypage user update

---

backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeEdit.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeEditDTO.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java

resume_edit 테이블 awards, experience 컬럼 삭제 및 items 컬럼 item, varchar(300)으로 수정

resume_edit 테이블 awards, experience 컬럼 삭제

---

backend/src/main/java/com/team2/resumeeditorproject/admin/config/SchedulerConfig.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/HistoryController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/domain/History.java
backend/src/main/java/com/team2/resumeeditorproject/admin/dto/HistoryDTO.java
backend/src/main/java/com/team2/resumeeditorproject/admin/interceptor/TrafficInterceptor.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeEditRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/HistoryRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/UserManagementServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeEdit.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeEditDTO.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/CustomAuthenticationFailureHandler.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/CorsMvcConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/RefreshRepository.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/RefreshService.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/RefreshServiceImpl.java

스케쥴러를 이용한 관리자 통계 페이지 추가, 로그인 시 error response 수정

history update, login issue

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/HistoryController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java

history save update, conflict method update

---

backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeEditController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/test/java/com/team2/resumeeditorproject/resume/service/ResumeEditServiceImplTest.java

자소서 상세페이지 조회 item(문항) 추가, resume-edit upload transaction 처리

자소서 상세페이지 조회 item(문항) 추가, resume-edit upload transaction 처리

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/HistoryController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminResumeRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/AdminUserRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/AdminServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/CustomUserDetailsService.java

user history update

---

backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/CustomAuthenticationFailureHandler.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/CorsMvcConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java

cors issue

---

backend/src/main/java/com/team2/resumeeditorproject/exception/ControllerExceptionAdvice.java
backend/src/main/java/com/team2/resumeeditorproject/exception/DelDateException.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/UserRepository.java

user delete update

---

backend/src/main/java/com/team2/resumeeditorproject/comment/domain/Comment.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/RatingRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditServiceImpl.java
backend/src/test/java/com/team2/resumeeditorproject/comment/service/CommentServiceImplTest.java

bookmark, rating

---

backend/src/main/java/com/team2/resumeeditorproject/admin/config/SchedulerConfig.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/AdminController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/HistoryController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/domain/History.java
backend/src/main/java/com/team2/resumeeditorproject/admin/domain/Traffic.java
backend/src/main/java/com/team2/resumeeditorproject/admin/interceptor/TrafficInterceptor.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/TrafficRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/TrafficService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/TrafficServiceImpl.java
backend/src/main/resources/application.yml

Traffic테이블 추가, 방문자 통계 수정, 표준시간대 추가(Asia/Seoul)

add traffic table, update traffic, update time-zone

---

backend/src/main/java/com/team2/resumeeditorproject/admin/config/SchedulerConfig.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/HistoryRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/repository/TrafficRepository.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/HistoryServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/TrafficService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/TrafficServiceImpl.java

update resume stat

---

backend/src/main/java/com/team2/resumeeditorproject/admin/config/SchedulerConfig.java
backend/src/main/java/com/team2/resumeeditorproject/admin/interceptor/TrafficInterceptor.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/TrafficServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/RefreshRepository.java

scheduler update, refresh query update

---

backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/ReissueController.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/RefreshRepository.java

refresh토큰 DB 저장 시 만료일 형식 수정(yyyy-MM-dd HH:mm:ss)

refresh update

---

backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/ReissueController.java

로그인시 refresh테이블에 저장되는 데이터의 동시성문제를 해결하기 위해 @Transactional 어노테이션 추가

refresh save update

---

backend/src/main/java/com/team2/resumeeditorproject/user/Jwt/LoginFilter.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/ReissueController.java
backend/src/main/java/com/team2/resumeeditorproject/user/domain/Refresh.java

refresh Entity - expiration 데이터타입 String->Data로 변경

refresh expiration datatype update

---

backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeGuideController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeItemsController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeOccupationController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/Guide.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/Items.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/Occupation.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/GuideDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ItemsDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/OccupationDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/GuideRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ItemsRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/OccupationRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/GuideService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/GuideServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ItemsService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ItemsServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/OccupationService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/OccupationServiceImpl.java

resume-guide updated

---

backend/src/main/java/com/team2/resumeeditorproject/admin/domain/Review.java
backend/src/main/java/com/team2/resumeeditorproject/admin/dto/ReviewDTO.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/main/java/com/team2/resumeeditorproject/user/domain/Occupation.java
backend/src/main/java/com/team2/resumeeditorproject/user/dto/OccupationDTO.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/OccupationRepository.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/RefreshRepository.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/OccupationService.java
backend/src/main/java/com/team2/resumeeditorproject/user/service/OccupationServiceImpl.java

만료 리프레시토큰 쿼리 수정, 직종 목록 가져오기 추가, review추가

refresh query update,occupation list update, admin review update

---

backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeBoard.java
backend/src/main/java/com/team2/resumeeditorproject/review/controller/ReviewController.java
backend/src/main/java/com/team2/resumeeditorproject/review/domain/Review.java
backend/src/main/java/com/team2/resumeeditorproject/review/dto/ReviewDTO.java
backend/src/main/java/com/team2/resumeeditorproject/review/repository/ReviewRepository.java
backend/src/main/java/com/team2/resumeeditorproject/review/service/ReviewService.java
backend/src/main/java/com/team2/resumeeditorproject/review/service/ReviewServiceImpl.java
backend/src/test/java/com/team2/resumeeditorproject/resume/controller/ResumeBoardControllerTest.java

review upload

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/ReviewManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/ReviewManagementService.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/ReviewManagementServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java

admin review selected

---

backend/src/main/java/com/team2/resumeeditorproject/admin/controller/LandingController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/controller/ReviewManagementController.java
backend/src/main/java/com/team2/resumeeditorproject/admin/service/ReviewManagementServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java

langing page stat update

---

backend/src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeGuideController.java
backend/src/main/java/com/team2/resumeeditorproject/resume/domain/ResumeGuide.java
backend/src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeGuideDTO.java
backend/src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeGuideRepository.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeGuideService.java
backend/src/main/java/com/team2/resumeeditorproject/resume/service/ResumeGuideServiceImpl.java
backend/src/main/java/com/team2/resumeeditorproject/user/config/SecurityConfig.java
backend/src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
backend/src/main/java/com/team2/resumeeditorproject/user/repository/OccupationListRepository.java

자소서 가이드 저장, 마이페이지 내 가이드 목록, 가이드 상세페이지 추가

resume guide insert, resume guide list update

---

src/main/java/com/team2/resumeeditorproject/resume/controller/ResumeRatingController.java
src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeRatingDTO.java
src/main/java/com/team2/resumeeditorproject/resume/repository/RatingRepository.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeRatingService.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeRatingServiceImpl.java

#122 resume 영역 리팩토링 (별점주기 기능 추가)

---

src/main/java/com/team2/resumeeditorproject/resume/repository/RatingRepository.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeRatingServiceImpl.java

setRating에서 resumeBoard에 rating, rating_count 업데이트하는 부분 추가

setRating 수정

---

src/main/java/com/team2/resumeeditorproject/bookmark/service/BookmarkServiceImpl.java

bookmarkDTO.getUserNo() -> loginUser.getUserNo()로 변

save Bookmark 수정

---

src/main/java/com/team2/resumeeditorproject/comment/controller/CommentController.java
src/main/java/com/team2/resumeeditorproject/comment/domain/Comment.java
src/main/java/com/team2/resumeeditorproject/comment/dto/CommentDTO.java
src/main/java/com/team2/resumeeditorproject/comment/repository/CommentRepository.java
src/main/java/com/team2/resumeeditorproject/comment/service/CommentService.java
src/main/java/com/team2/resumeeditorproject/comment/service/CommentServiceImpl.java
src/main/java/com/team2/resumeeditorproject/common/enumeration/ResultMessage.java
src/main/java/com/team2/resumeeditorproject/common/util/PageUtil.java
src/main/resources/application.yml
src/test/java/com/team2/resumeeditorproject/comment/service/CommentServiceImplTest.java

comment refactoring
pageUtil checkListEmpty 검색 결과가 없습니다 -> 결과가 없습니다 로 수정
ResultMessage에 Deleted 추가

comment refactoring

---

src/main/java/com/team2/resumeeditorproject/bookmark/dto/BookmarkDTO.java
src/main/java/com/team2/resumeeditorproject/bookmark/repository/BookmarkRepository.java
src/main/java/com/team2/resumeeditorproject/bookmark/service/BookmarkService.java
src/main/java/com/team2/resumeeditorproject/bookmark/service/BookmarkServiceImpl.java
src/main/java/com/team2/resumeeditorproject/resume/dto/ResumeEditDTO.java
src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeBoardRepository.java
src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeEditRepository.java
src/main/java/com/team2/resumeeditorproject/resume/repository/ResumeRepository.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardService.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeBoardServiceImpl.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditService.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeEditServiceImpl.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeService.java
src/main/java/com/team2/resumeeditorproject/resume/service/ResumeServiceImpl.java
src/main/java/com/team2/resumeeditorproject/user/controller/UserController.java
src/main/java/com/team2/resumeeditorproject/user/dto/ResumeEditDetailDTO.java

mypage 첨삭 목록, 첨삭 상세페이지, 즐겨찾기 목록 리팩토링

mypage 첨삭 목록, 첨삭 상세페이지, 즐겨찾기 목록 리팩토링
